### PR TITLE
Updated to handle true and false branches of a volatile flag...

### PR DESCRIPTION
**Pull request by arkohler**
…without generating multiple flag checks.

A code structure like
```
if_passed :flagname do
  bin 1
end
if_failed :flagname do
  bin 2
end

```
should still combine to an if/else structure even if :flagname is declared as volatile.  Currently the code generates two back-to-back flag comparisons with opposite value states.

### CODE REVIEW

**Comment by ginty** [comment]
Thanks for the PR.

Not sure that I really like treating the flag as volatile for some optimizations, but then ignoring it for others. Sure, it makes sense for this scenario, but are we setting up here for someone to complain in the future that it shouldn't be collapsing volatile flag references like this?

I would prefer one of the following solutions...

1) Enhance the API to allow you to code it to show that these conditions are mutually exclusive:

~~~ruby
if_passed :flagname, then: -> do
  bin 1
end, else: -> do
  bin 2
end 
~~~

2) Enhance the section of the code you have modified to look inside the first node. If it doesn't contain any test nodes, or doesn't explicitly set the flag, then we can safely assume that even though the flag is volatile, there is nothing in this case which could change its state between references.

What do you think of those?

**Comment by ginty** [comment]
In fact I think that coding syntax is already supported.

**Comment by arkohler** [comment]
Thanks for the comments @ginty.  I agree that we need to have consistent behavior.  Doing some optimizations but not others would make for a confusing interface.  As you said, though, it makes sense to optimize in this case.  In the pre-overhaul syntax, using if_flag followed by unless_flag was pretty much the only way of generating an if/else structure in the .tf file.
The main need behind volatile flags is that tests could change the state of the flag, therefore we needed a way to bypass the optimizations done across test nodes.  The current implementation takes that even further to the point of bypassing ALL optimizations, even when it generates an unnecessarily complicated flow.  We, as an Origen team, need to decide what the behavior should be and make all of the optimizations consistent with that behavior.  Personally, I tend to favor the one that simplifies the output flow.

**Comment by ginty** [comment]
I've implemented (2) from my earlier comment, does that work for you or are further exception cases needed?

**Comment by arkohler** [comment]
@ginty, I've looked through the commits and you've brought up an interesting case, one I hadn't really considered.  In the case of
```
test :test1
if_flag :flagname do
  test :test2
end
unless_flag :flagname do
  bin 1
end

```
This would generate two adjacent and opposite checks to the same flag.  If the first one fails, the second one necessarily passes, removing the need for a flag comparison (reducing to an if/else case).  If the first comparison passes, then test2 may change the result of the flag and you'd have to do a second comparison.  In our use case the flag checks are immediately after the test so we would put the flag check for test2 inside the if_flag block such as
```
test :test1
if_flag :flagname do
  test :test2
  unless_flag :flagname do
    bin 2
  end
end
unless_flag :flagname do
  bin 1
end

```
This way it's clear which flag comparison corresponds to which test.
Thinking further, in the case above, if both unless_flag blocks are rendered in the output as separate comparison blocks, then potentially both of them would be executed which may be undesirable.

**Comment by ginty** [comment]
At some point you may have to code it in a particular way to give the compiler more information about what you really mean.
For example, if you give the bin 1 branch higher priority by putting it first then it will collapse as you want:

~~~ruby
test :test1
unless_flag :flagname do
  bin 1
end
if_flag :flagname do
  test :test2
  unless_flag :flagname do
    bin 2
  end
end
~~~

Or you can code it to show that the outer branches should be treated as mutually exclusive:

~~~ruby
test :test1
if_flag :flagname then: -> do
  test :test2
  unless_flag :flagname do
    bin 2
  end
end, else: -> do
  bin 1
end
~~~

Otherwise, if we have told the compiler that `:flagname` should be considered volatile I don't see how it can know to convert the two outer checks into a mutually exclusive pair unless you give it more information to tell it to do that.

Do you have other ideas about how we should handle this?

**Comment by arkohler** [comment]
@ginty, I'll back up a little bit.  I'm trying to add what amounts to a call-back into the test interface.  Perhaps you'll have a better idea of how to do what I'm trying to do.  Whenever a test gets created there is an automatic flag check added to the fail branch.   This generally works fine.  The complication comes when there is an if_passed or if_failed call, or if there is an on_fail: or if_failed: flag passed.  I have to intercept the fail branch nodes and add them to the fail branch of the flag check within the fail branch of the test.  I have been exploring the best way to do that now that we have lambdas in the flow, and I have a bunch of test cases which generate wrong flows, but it might be related to how I insert the callback.
Right now, I'm doing this by setting the on_fail: key for each test generated.
`options[:on_fail] = -> { if_flag '$Alarm', then: -> { bin 1 }, else: previous_onfail_block }`

**Comment by ginty** [comment]
What does 'wrong flows' mean exactly?

I can imagine you might have problems with this if previous_onfail_block is itself a lambda, probably you would need to change what you have written above to be: `..., else: previous_onfail_block.call }`

**Comment by arkohler** [comment]
@ginty, I had tried using the call method but empirically discovered that it wasn't needed.
You asked about my wrong flows comment here's some examples from test cases I had put together which mimic the code being passed to ATP after being processed by my callback code in the interface:
```
  test :testC1, id: :tC1, on_fail: ->{
    if_flag "TestFlag" do
      bin 1
    end
    unless_flag "TestFlag" do
      test :testC2, id: :tC2, on_fail: ->{
        if_flag "TestFlag" do
          bin 1
        end
      }
      unless_flag "TestFlag" do
        bin 2, if_failed: :tC2
      end
    end
  }
```
 generates
```
  run_and_branch(testC1)
  then
  {
  }
  else
  {
    if @TESTFLAG == 1 then
    {
      stop_bin "", "fail", , bad, noreprobe, red, 1, over_on;
    }
    else
    {
      run_and_branch(testC2)
      then
      {
      }
      else
      {
        if @TESTFLAG == 1 then
        {
          stop_bin "", "fail", , bad, noreprobe, red, 1, over_on;
        }
        else
        {
        }
      }
      stop_bin "", "fail", , bad, noreprobe, red, 2, over_on;
    }
  }
```
In this one, the TestFlag is not declared as volatile, so I understand why the inner unless_flag is being optimized away.   However the bin 2 is being placed outside of the testC2 structure despite having if_failed: :tC2 in the call.
This next one is a slightly more compact version of the same flow, which has the same output.
```
  test :testD1, id: :tD1, on_fail: ->{
    bin 1, if_flag: "TestFlag"
    unless_flag "TestFlag", then: ->{
      test :testD2, id: :tD2, on_fail: ->{
        bin 1, if_flag: "TestFlag"
      }
      bin 2, if_failed: :tD2, unless_flag: "TestFlag"
    }
  }
```
In this example, the output is less correct:
```
  test :testG1, id: :tG1
  if_passed :tG1, then: ->{
    bin 2
  }, else: ->{
    if_flag "TestFlag", then: ->{ bin 1 }, else: ->{
      test :testG2, id: :tG2
      bin 3, if_failed: :tG2
    }
  }
```
Produces this output
```
  run_and_branch(testG1)
  then
  {
    stop_bin "", "fail", , bad, noreprobe, red, 2, over_on;
    if @TESTFLAG == 1 then
    {
      stop_bin "", "fail", , bad, noreprobe, red, 1, over_on;
    }
    else
    {
      run_and_branch(testG2)
      then
      {
      }
      else
      {
        @TG2_BEA7F3B_FAILED = 1;
      }
      if @TG2_BEA7F3B_FAILED == 1 then
      {
        stop_bin "", "fail", , bad, noreprobe, red, 3, over_on;
      }
      else
      {
      }
    }
  }
  else
  {
  }
```
For some reason, both the then: and else: branches of the if_passed :tG1 are getting merged together into the passed path.  Also, the flag by testG2 is not getting optimized away, but that's a smaller issue.  If I change the if_passed :tG1 to if_failed :tG1, then the whole block moves into the fail branch, including the bin 2.

**Comment by ginty** [comment]
Thanks @arkohler, that helps a lot and there seems to be some bugs here that we need to sort out.

Could you convert these to some tests cases and push to this PR? I can help work out what is wrong once we have the failing test cases.

I have this spec file which you can add them to and which is a catch all for general test cases based on real life issues that have been identified - https://github.com/Origen-SDK/atp/blob/master/spec/optimization_spec.rb

**Comment by arkohler** [comment]
@ginty.  I created the test cases in optimization_spec.rb, but the resulting AST appears to be generally correct.  The problem must be coming after the AST is generated.  I'm having some git trouble getting the push through, but in the meantime, here's the resulting AST.
For the first case above:
```
      s(:flow,
        s(:name, "sort1"),
        s(:test,
          s(:object, "test1"),
          s(:id, "t1"),
          s(:on_fail,
            s(:if_flag, "TestFlag",
              s(:set_result, "fail",
                s(:bin, 1)),
              s(:else,
                s(:test,
                  s(:object, "test2"),
                  s(:id, "t2"),
                  s(:on_fail,
                    s(:if_flag, "TestFlag",
                      s(:set_result, "fail",
                        s(:bin, 1))))),
                s(:if_failed, "t2",
                  s(:set_result, "fail",
                    s(:bin, 2))))))))

```
And the second case (using if_failed :t1)
```
      s(:flow,
        s(:name, "sort1"),
        s(:test,
          s(:object, "test1"),
          s(:id, "t1"),
          s(:on_fail,
            s(:set_result, "fail",
              s(:bin, 2)),
            s(:else,
              s(:if_flag, "TestFlag",
                s(:set_result, "fail",
                  s(:bin, 1)),
                s(:else,
                  s(:test,
                    s(:object, "test2"),
                    s(:id, "t2"),
                    s(:on_fail,
                      s(:set_flag, "t2_FAILED", "auto_generated"))),
                  s(:if_flag, "t2_FAILED",
                    s(:set_result, "fail",
                      s(:bin, 3)))))))))

```

**Comment by ginty** [comment]
@arkohler, that looks like that raw AST, likely the error occurs during the processing/optimizations.

Within that test spec the `ast` method will return the optimized AST.

Normally what I do when creating these tests is put a debugger into the test after the AST has been created. Then call the 'ast' method from the debugger and paste that in as a starting point. Then review it and hand modify as necessary to make it what it should be if the current output is found to be wrong.

**Comment by arkohler** [comment]
@ginty, actually those examples above are post-optimization, using the ast command after it was generated.  Now that I knew to look for it, the result of atp.raw is generally similar though with a couple of differences.  I've started digging into the AST processing/optimization code and will let you know if I find anything.  However, it must be post-AST optimization where the logically ok AST becomes the incorrect 93k flow.

**Comment by ginty** [comment]
@arkohler, I see.
The reason I thought it was raw is that it contains an `if_failed` node, which appear in the raw version but which should all be converted to either a set_flag/if_flag pair, or be nested within an on_fail node in the processed/optimized version.

The downstream V93K flow renderer won't know what to do with an `if_failed` node, so I think we can already see the problem at this level.

It looks like maybe the children of `else` nodes are not being processed.

**Comment by ginty** [comment]
I think maybe this bit https://github.com/Origen-SDK/atp/blob/master/lib/atp/processors/relationship.rb#L129

Should be changed to:

~~~ruby
# Original, does not process the children of test nodes
if node.type == :group
  node.updated(nil, process_all(node))
else
  node
end

# Remove if statement change to
node.updated(nil, process_all(node.children))
~~~

**Comment by arkohler** [comment]
Hi @ginty,
I've been somewhat busy with other pressing items and haven't had the chance to look at this in the past couple of days.  I did try your suggestion above and ended up with a recursion-too-deep error when running origen_testers examples.
I have added the requested test cases to a new PR #8 since this branch seems to have git confused.

**Comment by ginty** [comment]
Thanks for the new test cases @arkohler, that first one in particular gives it quite a workout!

To handle the first one, I've added a new validator which will now raise an error if you present it with something like that (nested if/unless_flag with opposite states) without declaring the flag as volatile. Otherwise it won't know what to do with it.

Once you add the volatile, it now produces something which I believe to be correct, see what you think.

A further enhancement could be to create the volatile definition on the fly internally if it sees something like that, rather than raise the error and have the user do it. You can let me know what you think of that, I can see advantages to both and don't have a strong opinion one way or the other.

Note that this PR still contains the earlier update which means that it will now optimize cases like this since it knows that what is contained within the first `if_passed` branch cannot change the state of the flag.

~~~ruby
volatile :flagname
if_passed :flagname do
  bin 1
end
if_failed :flagname do
  bin 2
end
~~~

I think that's still a worthwhile enhancement and we should keep it, even though it did nothing to help the eventual root cause in this case.

Agree?

**Review by ginty — APPROVED** [review]

**Comment by ginty** [comment]
@arkohler, I'm going to hold off merging this until you bless it. No immediate rush from my pov, but just to let you know in case you forgot about it.
Thanks!

**Pull request merged**
