### PR TITLE
Add bin (hard and soft) descriptions to node properties

### PR DESCRIPTION
**Pull request by rlaj**
Track bin description as a property of a node so that it can be used during program rendering if desired.

### CODE REVIEW

**Comment by ginty** [comment]
Hi @rlaj,

This looks better, though still not quite right.

In an AST the fields are recognized by position and not by a named key, the fact that you had to add the attributes to Node indicates that you have gone down a wrong path slightly. Note that the existing file, line_number, description attributes are references to the test program flow source file from where the code that created the node originated - it is meta data that is there to help provide debug feedback, it does not carry semantic information about the flow represented by the AST. The generated flow should be the same if all the meta data was stripped out.

I would have a read at this if you want some more background info, it does take a while to digest and think about: http://whitequark.github.io/ast/frames.html

So, we are really looking for this to produce bin nodes that look like this:

s(:bin, 5)
s(:bin, 5, "some description")

It is the responsiblity of the flow renderer to understand that a bin node can take these two forms and if present the description will always be the second argument.

Now it is very possible that an OrigenTester update is required in parallel with this. I did have a quick look before and I noticed that I had earlier gone down a wrong path of using a dedicated bin_description node.

Let me know if you want to have a call or something to walk through this, more than happy to do that.

**Comment by rlaj** [comment]
Made the updates.  Not completely sure I like the 'desc' method, but everything behaves as expected/requested/suggested.

**Review by ginty — CHANGES_REQUESTED** [review]
Almost there, but yeah I think you should remove the desc method, its too specific to this particular kind of node.

The handler for a for a bin type node would just process it like this:

~~~ruby
n = node.to_a
bin = node[0]
desc = node[1]
~~~

**Comment by rlaj** [comment]
Removed the desc method.

**Review by ginty — APPROVED** [review]

**Pull request merged**
